#!/usr/bin/env node
/**
 * Generate public/sitemap.xml with static routes + demo catalog URLs.
 * Set VITE_SITE_URL or SITE_URL (default https://1px.app)
 */
import { writeFileSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const base = (process.env.VITE_SITE_URL || process.env.SITE_URL || "https://1px.app").replace(/\/$/, "");

const catalogUid = (i) => {
  const hex = i.toString(16).padStart(2, "0");
  return `00000000-0000-0000-0000-00000000a0${hex}`;
};
const catalogProjectId = (i) => {
  const hex = i.toString(16).padStart(2, "0");
  return `00000000-0000-0000-0002-0000000000${hex}`;
};
const studioSlugs = [
  "doi-studio", "lotus-lab", "mango-pixel", "inkwell-co", "frame-field",
  "sundaze-crafts", "soundwave-bkk", "pixel-garden", "yim-studio", "talay-creative",
];

const staticPaths = [
  { loc: "/", priority: "1.0", changefreq: "daily" },
  { loc: "/jobs", priority: "0.9", changefreq: "daily" },
  { loc: "/advertise", priority: "0.7", changefreq: "weekly" },
  { loc: "/legal/privacy", priority: "0.3", changefreq: "monthly" },
  { loc: "/legal/terms", priority: "0.3", changefreq: "monthly" },
  { loc: "/legal/cookies", priority: "0.2", changefreq: "monthly" },
  { loc: "/legal/rights", priority: "0.2", changefreq: "monthly" },
];

const urls = [
  ...staticPaths,
  ...Array.from({ length: 20 }, (_, i) => ({
    loc: `/project/${catalogProjectId(i)}`,
    priority: "0.8",
    changefreq: "weekly",
  })),
  ...Array.from({ length: 20 }, (_, i) => ({
    loc: `/u/${catalogUid(i)}`,
    priority: "0.7",
    changefreq: "weekly",
  })),
  ...studioSlugs.map((slug) => ({
    loc: `/s/${slug}`,
    priority: "0.6",
    changefreq: "weekly",
  })),
];

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate-sitemap.mjs — run: npm run sitemap:gen -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls
  .map(
    (u) => `  <url>
    <loc>${base}${u.loc}</loc>
    <changefreq>${u.changefreq}</changefreq>
    <priority>${u.priority}</priority>
  </url>`,
  )
  .join("\n")}
</urlset>
`;

const out = join(root, "public", "sitemap.xml");
writeFileSync(out, xml, "utf8");
console.log(`Wrote ${urls.length} URLs to public/sitemap.xml (base: ${base})`);
